if(EXISTS "/app/build-docker/components/serialization/tests/test_serialization_tests-b12d07c.cmake")
  include("/app/build-docker/components/serialization/tests/test_serialization_tests-b12d07c.cmake")
else()
  add_test(test_serialization_NOT_BUILT-b12d07c test_serialization_NOT_BUILT-b12d07c)
endif()
