if(EXISTS "/app/build-docker/integration/c/test/test_c_otterbrix_tests-b12d07c.cmake")
  include("/app/build-docker/integration/c/test/test_c_otterbrix_tests-b12d07c.cmake")
else()
  add_test(test_c_otterbrix_NOT_BUILT-b12d07c test_c_otterbrix_NOT_BUILT-b12d07c)
endif()
