if(EXISTS "/app/build-docker/components/types/tests/test_types_tests-b12d07c.cmake")
  include("/app/build-docker/components/types/tests/test_types_tests-b12d07c.cmake")
else()
  add_test(test_types_NOT_BUILT-b12d07c test_types_NOT_BUILT-b12d07c)
endif()
