if(EXISTS "/app/build-docker/components/expressions/test/test_expressions_tests-b12d07c.cmake")
  include("/app/build-docker/components/expressions/test/test_expressions_tests-b12d07c.cmake")
else()
  add_test(test_expressions_NOT_BUILT-b12d07c test_expressions_NOT_BUILT-b12d07c)
endif()
