if(EXISTS "/app/build-docker/components/sql/test/test_sql_tests-b12d07c.cmake")
  include("/app/build-docker/components/sql/test/test_sql_tests-b12d07c.cmake")
else()
  add_test(test_sql_NOT_BUILT-b12d07c test_sql_NOT_BUILT-b12d07c)
endif()
