if(EXISTS "/app/build-docker/components/oid/test/test_oid_tests-b12d07c.cmake")
  include("/app/build-docker/components/oid/test/test_oid_tests-b12d07c.cmake")
else()
  add_test(test_oid_NOT_BUILT-b12d07c test_oid_NOT_BUILT-b12d07c)
endif()
