add_test( components::oid::is_valid /app/build-docker/components/oid/test/test_oid components::oid::is_valid  )
set_tests_properties( components::oid::is_valid PROPERTIES WORKING_DIRECTORY /app/build-docker/components/oid/test)
add_test( components::oid::initialization /app/build-docker/components/oid/test/test_oid components::oid::initialization  )
set_tests_properties( components::oid::initialization PROPERTIES WORKING_DIRECTORY /app/build-docker/components/oid/test)
add_test( components::oid::operators /app/build-docker/components/oid/test/test_oid components::oid::operators  )
set_tests_properties( components::oid::operators PROPERTIES WORKING_DIRECTORY /app/build-docker/components/oid/test)
add_test( [==[components::oid::generate by time]==] /app/build-docker/components/oid/test/test_oid [==[components::oid::generate by time]==]  )
set_tests_properties( [==[components::oid::generate by time]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/components/oid/test)
set( test_oid_TESTS components::oid::is_valid components::oid::initialization components::oid::operators [==[components::oid::generate by time]==])
