add_test( core::tests::empty_buffer /app/build-docker/core/tests/test_core core::tests::empty_buffer  )
set_tests_properties( core::tests::empty_buffer PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( core::tests::memory_resource /app/build-docker/core/tests/test_core core::tests::memory_resource  )
set_tests_properties( core::tests::memory_resource PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( core::tests::copy_from_raw_pointer /app/build-docker/core/tests/test_core core::tests::copy_from_raw_pointer  )
set_tests_properties( core::tests::copy_from_raw_pointer PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( core::tests::copy_from_nullptr /app/build-docker/core/tests/test_core core::tests::copy_from_nullptr  )
set_tests_properties( core::tests::copy_from_nullptr PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( core::tests::copy_constructor /app/build-docker/core/tests/test_core core::tests::copy_constructor  )
set_tests_properties( core::tests::copy_constructor PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( core::tests::copy_capacity_larger_than_size /app/build-docker/core/tests/test_core core::tests::copy_capacity_larger_than_size  )
set_tests_properties( core::tests::copy_capacity_larger_than_size PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( core::tests::copy_constructor_explicit_memory_resource /app/build-docker/core/tests/test_core core::tests::copy_constructor_explicit_memory_resource  )
set_tests_properties( core::tests::copy_constructor_explicit_memory_resource PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( core::tests::copy_capacity_larger_than_size_explicit_memory_resource /app/build-docker/core/tests/test_core core::tests::copy_capacity_larger_than_size_explicit_memory_resource  )
set_tests_properties( core::tests::copy_capacity_larger_than_size_explicit_memory_resource PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( core::tests::move_constructor /app/build-docker/core/tests/test_core core::tests::move_constructor  )
set_tests_properties( core::tests::move_constructor PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( core::tests::move_assignment_to_default /app/build-docker/core/tests/test_core core::tests::move_assignment_to_default  )
set_tests_properties( core::tests::move_assignment_to_default PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( core::tests::move_assignment /app/build-docker/core/tests/test_core core::tests::move_assignment  )
set_tests_properties( core::tests::move_assignment PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( core::tests::self_move_assignment /app/build-docker/core/tests/test_core core::tests::self_move_assignment  )
set_tests_properties( core::tests::self_move_assignment PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( core::tests::resize_smaller /app/build-docker/core/tests/test_core core::tests::resize_smaller  )
set_tests_properties( core::tests::resize_smaller PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::resize bigger]==] /app/build-docker/core/tests/test_core [==[core::tests::resize bigger]==]  )
set_tests_properties( [==[core::tests::resize bigger]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::reserve smaller]==] /app/build-docker/core/tests/test_core [==[core::tests::reserve smaller]==]  )
set_tests_properties( [==[core::tests::reserve smaller]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::reserve bigger]==] /app/build-docker/core/tests/test_core [==[core::tests::reserve bigger]==]  )
set_tests_properties( [==[core::tests::reserve bigger]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::unitialized - bool]==] /app/build-docker/core/tests/test_core [==[core::tests::unitialized - bool]==]  )
set_tests_properties( [==[core::tests::unitialized - bool]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::unitialized - std::int8_t]==] /app/build-docker/core/tests/test_core [==[core::tests::unitialized - std::int8_t]==]  )
set_tests_properties( [==[core::tests::unitialized - std::int8_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::unitialized - std::int16_t]==] /app/build-docker/core/tests/test_core [==[core::tests::unitialized - std::int16_t]==]  )
set_tests_properties( [==[core::tests::unitialized - std::int16_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::unitialized - std::int32_t]==] /app/build-docker/core/tests/test_core [==[core::tests::unitialized - std::int32_t]==]  )
set_tests_properties( [==[core::tests::unitialized - std::int32_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::unitialized - std::int64_t]==] /app/build-docker/core/tests/test_core [==[core::tests::unitialized - std::int64_t]==]  )
set_tests_properties( [==[core::tests::unitialized - std::int64_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::unitialized - float]==] /app/build-docker/core/tests/test_core [==[core::tests::unitialized - float]==]  )
set_tests_properties( [==[core::tests::unitialized - float]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::unitialized - double]==] /app/build-docker/core/tests/test_core [==[core::tests::unitialized - double]==]  )
set_tests_properties( [==[core::tests::unitialized - double]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::initialValue - bool]==] /app/build-docker/core/tests/test_core [==[core::tests::initialValue - bool]==]  )
set_tests_properties( [==[core::tests::initialValue - bool]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::initialValue - std::int8_t]==] /app/build-docker/core/tests/test_core [==[core::tests::initialValue - std::int8_t]==]  )
set_tests_properties( [==[core::tests::initialValue - std::int8_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::initialValue - std::int16_t]==] /app/build-docker/core/tests/test_core [==[core::tests::initialValue - std::int16_t]==]  )
set_tests_properties( [==[core::tests::initialValue - std::int16_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::initialValue - std::int32_t]==] /app/build-docker/core/tests/test_core [==[core::tests::initialValue - std::int32_t]==]  )
set_tests_properties( [==[core::tests::initialValue - std::int32_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::initialValue - std::int64_t]==] /app/build-docker/core/tests/test_core [==[core::tests::initialValue - std::int64_t]==]  )
set_tests_properties( [==[core::tests::initialValue - std::int64_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::initialValue - float]==] /app/build-docker/core/tests/test_core [==[core::tests::initialValue - float]==]  )
set_tests_properties( [==[core::tests::initialValue - float]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::initialValue - double]==] /app/build-docker/core/tests/test_core [==[core::tests::initialValue - double]==]  )
set_tests_properties( [==[core::tests::initialValue - double]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::const_ptr_data - bool]==] /app/build-docker/core/tests/test_core [==[core::tests::const_ptr_data - bool]==]  )
set_tests_properties( [==[core::tests::const_ptr_data - bool]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::const_ptr_data - std::int8_t]==] /app/build-docker/core/tests/test_core [==[core::tests::const_ptr_data - std::int8_t]==]  )
set_tests_properties( [==[core::tests::const_ptr_data - std::int8_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::const_ptr_data - std::int16_t]==] /app/build-docker/core/tests/test_core [==[core::tests::const_ptr_data - std::int16_t]==]  )
set_tests_properties( [==[core::tests::const_ptr_data - std::int16_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::const_ptr_data - std::int32_t]==] /app/build-docker/core/tests/test_core [==[core::tests::const_ptr_data - std::int32_t]==]  )
set_tests_properties( [==[core::tests::const_ptr_data - std::int32_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::const_ptr_data - std::int64_t]==] /app/build-docker/core/tests/test_core [==[core::tests::const_ptr_data - std::int64_t]==]  )
set_tests_properties( [==[core::tests::const_ptr_data - std::int64_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::const_ptr_data - float]==] /app/build-docker/core/tests/test_core [==[core::tests::const_ptr_data - float]==]  )
set_tests_properties( [==[core::tests::const_ptr_data - float]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::const_ptr_data - double]==] /app/build-docker/core/tests/test_core [==[core::tests::const_ptr_data - double]==]  )
set_tests_properties( [==[core::tests::const_ptr_data - double]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::copy_ctor - bool]==] /app/build-docker/core/tests/test_core [==[core::tests::copy_ctor - bool]==]  )
set_tests_properties( [==[core::tests::copy_ctor - bool]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::copy_ctor - std::int8_t]==] /app/build-docker/core/tests/test_core [==[core::tests::copy_ctor - std::int8_t]==]  )
set_tests_properties( [==[core::tests::copy_ctor - std::int8_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::copy_ctor - std::int16_t]==] /app/build-docker/core/tests/test_core [==[core::tests::copy_ctor - std::int16_t]==]  )
set_tests_properties( [==[core::tests::copy_ctor - std::int16_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::copy_ctor - std::int32_t]==] /app/build-docker/core/tests/test_core [==[core::tests::copy_ctor - std::int32_t]==]  )
set_tests_properties( [==[core::tests::copy_ctor - std::int32_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::copy_ctor - std::int64_t]==] /app/build-docker/core/tests/test_core [==[core::tests::copy_ctor - std::int64_t]==]  )
set_tests_properties( [==[core::tests::copy_ctor - std::int64_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::copy_ctor - float]==] /app/build-docker/core/tests/test_core [==[core::tests::copy_ctor - float]==]  )
set_tests_properties( [==[core::tests::copy_ctor - float]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::copy_ctor - double]==] /app/build-docker/core/tests/test_core [==[core::tests::copy_ctor - double]==]  )
set_tests_properties( [==[core::tests::copy_ctor - double]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::move_ctor - bool]==] /app/build-docker/core/tests/test_core [==[core::tests::move_ctor - bool]==]  )
set_tests_properties( [==[core::tests::move_ctor - bool]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::move_ctor - std::int8_t]==] /app/build-docker/core/tests/test_core [==[core::tests::move_ctor - std::int8_t]==]  )
set_tests_properties( [==[core::tests::move_ctor - std::int8_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::move_ctor - std::int16_t]==] /app/build-docker/core/tests/test_core [==[core::tests::move_ctor - std::int16_t]==]  )
set_tests_properties( [==[core::tests::move_ctor - std::int16_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::move_ctor - std::int32_t]==] /app/build-docker/core/tests/test_core [==[core::tests::move_ctor - std::int32_t]==]  )
set_tests_properties( [==[core::tests::move_ctor - std::int32_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::move_ctor - std::int64_t]==] /app/build-docker/core/tests/test_core [==[core::tests::move_ctor - std::int64_t]==]  )
set_tests_properties( [==[core::tests::move_ctor - std::int64_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::move_ctor - float]==] /app/build-docker/core/tests/test_core [==[core::tests::move_ctor - float]==]  )
set_tests_properties( [==[core::tests::move_ctor - float]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::move_ctor - double]==] /app/build-docker/core/tests/test_core [==[core::tests::move_ctor - double]==]  )
set_tests_properties( [==[core::tests::move_ctor - double]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::set_value - bool]==] /app/build-docker/core/tests/test_core [==[core::tests::set_value - bool]==]  )
set_tests_properties( [==[core::tests::set_value - bool]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::set_value - std::int8_t]==] /app/build-docker/core/tests/test_core [==[core::tests::set_value - std::int8_t]==]  )
set_tests_properties( [==[core::tests::set_value - std::int8_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::set_value - std::int16_t]==] /app/build-docker/core/tests/test_core [==[core::tests::set_value - std::int16_t]==]  )
set_tests_properties( [==[core::tests::set_value - std::int16_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::set_value - std::int32_t]==] /app/build-docker/core/tests/test_core [==[core::tests::set_value - std::int32_t]==]  )
set_tests_properties( [==[core::tests::set_value - std::int32_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::set_value - std::int64_t]==] /app/build-docker/core/tests/test_core [==[core::tests::set_value - std::int64_t]==]  )
set_tests_properties( [==[core::tests::set_value - std::int64_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::set_value - float]==] /app/build-docker/core/tests/test_core [==[core::tests::set_value - float]==]  )
set_tests_properties( [==[core::tests::set_value - float]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::set_value - double]==] /app/build-docker/core/tests/test_core [==[core::tests::set_value - double]==]  )
set_tests_properties( [==[core::tests::set_value - double]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::set_value_to_zero - bool]==] /app/build-docker/core/tests/test_core [==[core::tests::set_value_to_zero - bool]==]  )
set_tests_properties( [==[core::tests::set_value_to_zero - bool]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::set_value_to_zero - std::int8_t]==] /app/build-docker/core/tests/test_core [==[core::tests::set_value_to_zero - std::int8_t]==]  )
set_tests_properties( [==[core::tests::set_value_to_zero - std::int8_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::set_value_to_zero - std::int16_t]==] /app/build-docker/core/tests/test_core [==[core::tests::set_value_to_zero - std::int16_t]==]  )
set_tests_properties( [==[core::tests::set_value_to_zero - std::int16_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::set_value_to_zero - std::int32_t]==] /app/build-docker/core/tests/test_core [==[core::tests::set_value_to_zero - std::int32_t]==]  )
set_tests_properties( [==[core::tests::set_value_to_zero - std::int32_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::set_value_to_zero - std::int64_t]==] /app/build-docker/core/tests/test_core [==[core::tests::set_value_to_zero - std::int64_t]==]  )
set_tests_properties( [==[core::tests::set_value_to_zero - std::int64_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::set_value_to_zero - float]==] /app/build-docker/core/tests/test_core [==[core::tests::set_value_to_zero - float]==]  )
set_tests_properties( [==[core::tests::set_value_to_zero - float]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::set_value_to_zero - double]==] /app/build-docker/core/tests/test_core [==[core::tests::set_value_to_zero - double]==]  )
set_tests_properties( [==[core::tests::set_value_to_zero - double]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::memory_resource - std::int8_t]==] /app/build-docker/core/tests/test_core [==[core::tests::memory_resource - std::int8_t]==]  )
set_tests_properties( [==[core::tests::memory_resource - std::int8_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::memory_resource - std::int32_t]==] /app/build-docker/core/tests/test_core [==[core::tests::memory_resource - std::int32_t]==]  )
set_tests_properties( [==[core::tests::memory_resource - std::int32_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::memory_resource - std::uint64_t]==] /app/build-docker/core/tests/test_core [==[core::tests::memory_resource - std::uint64_t]==]  )
set_tests_properties( [==[core::tests::memory_resource - std::uint64_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::memory_resource - float]==] /app/build-docker/core/tests/test_core [==[core::tests::memory_resource - float]==]  )
set_tests_properties( [==[core::tests::memory_resource - float]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::memory_resource - double]==] /app/build-docker/core/tests/test_core [==[core::tests::memory_resource - double]==]  )
set_tests_properties( [==[core::tests::memory_resource - double]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::zero_size_constructor - std::int8_t]==] /app/build-docker/core/tests/test_core [==[core::tests::zero_size_constructor - std::int8_t]==]  )
set_tests_properties( [==[core::tests::zero_size_constructor - std::int8_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::zero_size_constructor - std::int32_t]==] /app/build-docker/core/tests/test_core [==[core::tests::zero_size_constructor - std::int32_t]==]  )
set_tests_properties( [==[core::tests::zero_size_constructor - std::int32_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::zero_size_constructor - std::uint64_t]==] /app/build-docker/core/tests/test_core [==[core::tests::zero_size_constructor - std::uint64_t]==]  )
set_tests_properties( [==[core::tests::zero_size_constructor - std::uint64_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::zero_size_constructor - float]==] /app/build-docker/core/tests/test_core [==[core::tests::zero_size_constructor - float]==]  )
set_tests_properties( [==[core::tests::zero_size_constructor - float]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::zero_size_constructor - double]==] /app/build-docker/core/tests/test_core [==[core::tests::zero_size_constructor - double]==]  )
set_tests_properties( [==[core::tests::zero_size_constructor - double]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::non_zero_size_constructor - std::int8_t]==] /app/build-docker/core/tests/test_core [==[core::tests::non_zero_size_constructor - std::int8_t]==]  )
set_tests_properties( [==[core::tests::non_zero_size_constructor - std::int8_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::non_zero_size_constructor - std::int32_t]==] /app/build-docker/core/tests/test_core [==[core::tests::non_zero_size_constructor - std::int32_t]==]  )
set_tests_properties( [==[core::tests::non_zero_size_constructor - std::int32_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::non_zero_size_constructor - std::uint64_t]==] /app/build-docker/core/tests/test_core [==[core::tests::non_zero_size_constructor - std::uint64_t]==]  )
set_tests_properties( [==[core::tests::non_zero_size_constructor - std::uint64_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::non_zero_size_constructor - float]==] /app/build-docker/core/tests/test_core [==[core::tests::non_zero_size_constructor - float]==]  )
set_tests_properties( [==[core::tests::non_zero_size_constructor - float]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::non_zero_size_constructor - double]==] /app/build-docker/core/tests/test_core [==[core::tests::non_zero_size_constructor - double]==]  )
set_tests_properties( [==[core::tests::non_zero_size_constructor - double]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::copy_constructor - std::int8_t]==] /app/build-docker/core/tests/test_core [==[core::tests::copy_constructor - std::int8_t]==]  )
set_tests_properties( [==[core::tests::copy_constructor - std::int8_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::copy_constructor - std::int32_t]==] /app/build-docker/core/tests/test_core [==[core::tests::copy_constructor - std::int32_t]==]  )
set_tests_properties( [==[core::tests::copy_constructor - std::int32_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::copy_constructor - std::uint64_t]==] /app/build-docker/core/tests/test_core [==[core::tests::copy_constructor - std::uint64_t]==]  )
set_tests_properties( [==[core::tests::copy_constructor - std::uint64_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::copy_constructor - float]==] /app/build-docker/core/tests/test_core [==[core::tests::copy_constructor - float]==]  )
set_tests_properties( [==[core::tests::copy_constructor - float]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::copy_constructor - double]==] /app/build-docker/core/tests/test_core [==[core::tests::copy_constructor - double]==]  )
set_tests_properties( [==[core::tests::copy_constructor - double]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::resize_smaller - std::int8_t]==] /app/build-docker/core/tests/test_core [==[core::tests::resize_smaller - std::int8_t]==]  )
set_tests_properties( [==[core::tests::resize_smaller - std::int8_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::resize_smaller - std::int32_t]==] /app/build-docker/core/tests/test_core [==[core::tests::resize_smaller - std::int32_t]==]  )
set_tests_properties( [==[core::tests::resize_smaller - std::int32_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::resize_smaller - std::uint64_t]==] /app/build-docker/core/tests/test_core [==[core::tests::resize_smaller - std::uint64_t]==]  )
set_tests_properties( [==[core::tests::resize_smaller - std::uint64_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::resize_smaller - float]==] /app/build-docker/core/tests/test_core [==[core::tests::resize_smaller - float]==]  )
set_tests_properties( [==[core::tests::resize_smaller - float]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::resize_smaller - double]==] /app/build-docker/core/tests/test_core [==[core::tests::resize_smaller - double]==]  )
set_tests_properties( [==[core::tests::resize_smaller - double]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::resize_larger - std::int8_t]==] /app/build-docker/core/tests/test_core [==[core::tests::resize_larger - std::int8_t]==]  )
set_tests_properties( [==[core::tests::resize_larger - std::int8_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::resize_larger - std::int32_t]==] /app/build-docker/core/tests/test_core [==[core::tests::resize_larger - std::int32_t]==]  )
set_tests_properties( [==[core::tests::resize_larger - std::int32_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::resize_larger - std::uint64_t]==] /app/build-docker/core/tests/test_core [==[core::tests::resize_larger - std::uint64_t]==]  )
set_tests_properties( [==[core::tests::resize_larger - std::uint64_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::resize_larger - float]==] /app/build-docker/core/tests/test_core [==[core::tests::resize_larger - float]==]  )
set_tests_properties( [==[core::tests::resize_larger - float]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::resize_larger - double]==] /app/build-docker/core/tests/test_core [==[core::tests::resize_larger - double]==]  )
set_tests_properties( [==[core::tests::resize_larger - double]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::reserve_smaller - std::int8_t]==] /app/build-docker/core/tests/test_core [==[core::tests::reserve_smaller - std::int8_t]==]  )
set_tests_properties( [==[core::tests::reserve_smaller - std::int8_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::reserve_smaller - std::int32_t]==] /app/build-docker/core/tests/test_core [==[core::tests::reserve_smaller - std::int32_t]==]  )
set_tests_properties( [==[core::tests::reserve_smaller - std::int32_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::reserve_smaller - std::uint64_t]==] /app/build-docker/core/tests/test_core [==[core::tests::reserve_smaller - std::uint64_t]==]  )
set_tests_properties( [==[core::tests::reserve_smaller - std::uint64_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::reserve_smaller - float]==] /app/build-docker/core/tests/test_core [==[core::tests::reserve_smaller - float]==]  )
set_tests_properties( [==[core::tests::reserve_smaller - float]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::reserve_smaller - double]==] /app/build-docker/core/tests/test_core [==[core::tests::reserve_smaller - double]==]  )
set_tests_properties( [==[core::tests::reserve_smaller - double]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::reserve_larger - std::int8_t]==] /app/build-docker/core/tests/test_core [==[core::tests::reserve_larger - std::int8_t]==]  )
set_tests_properties( [==[core::tests::reserve_larger - std::int8_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::reserve_larger - std::int32_t]==] /app/build-docker/core/tests/test_core [==[core::tests::reserve_larger - std::int32_t]==]  )
set_tests_properties( [==[core::tests::reserve_larger - std::int32_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::reserve_larger - std::uint64_t]==] /app/build-docker/core/tests/test_core [==[core::tests::reserve_larger - std::uint64_t]==]  )
set_tests_properties( [==[core::tests::reserve_larger - std::uint64_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::reserve_larger - float]==] /app/build-docker/core/tests/test_core [==[core::tests::reserve_larger - float]==]  )
set_tests_properties( [==[core::tests::reserve_larger - float]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::reserve_larger - double]==] /app/build-docker/core/tests/test_core [==[core::tests::reserve_larger - double]==]  )
set_tests_properties( [==[core::tests::reserve_larger - double]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::resize_to_zero - std::int8_t]==] /app/build-docker/core/tests/test_core [==[core::tests::resize_to_zero - std::int8_t]==]  )
set_tests_properties( [==[core::tests::resize_to_zero - std::int8_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::resize_to_zero - std::int32_t]==] /app/build-docker/core/tests/test_core [==[core::tests::resize_to_zero - std::int32_t]==]  )
set_tests_properties( [==[core::tests::resize_to_zero - std::int32_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::resize_to_zero - std::uint64_t]==] /app/build-docker/core/tests/test_core [==[core::tests::resize_to_zero - std::uint64_t]==]  )
set_tests_properties( [==[core::tests::resize_to_zero - std::uint64_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::resize_to_zero - float]==] /app/build-docker/core/tests/test_core [==[core::tests::resize_to_zero - float]==]  )
set_tests_properties( [==[core::tests::resize_to_zero - float]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::resize_to_zero - double]==] /app/build-docker/core/tests/test_core [==[core::tests::resize_to_zero - double]==]  )
set_tests_properties( [==[core::tests::resize_to_zero - double]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::release - std::int8_t]==] /app/build-docker/core/tests/test_core [==[core::tests::release - std::int8_t]==]  )
set_tests_properties( [==[core::tests::release - std::int8_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::release - std::int32_t]==] /app/build-docker/core/tests/test_core [==[core::tests::release - std::int32_t]==]  )
set_tests_properties( [==[core::tests::release - std::int32_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::release - std::uint64_t]==] /app/build-docker/core/tests/test_core [==[core::tests::release - std::uint64_t]==]  )
set_tests_properties( [==[core::tests::release - std::uint64_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::release - float]==] /app/build-docker/core/tests/test_core [==[core::tests::release - float]==]  )
set_tests_properties( [==[core::tests::release - float]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::release - double]==] /app/build-docker/core/tests/test_core [==[core::tests::release - double]==]  )
set_tests_properties( [==[core::tests::release - double]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::element_pointer - std::int8_t]==] /app/build-docker/core/tests/test_core [==[core::tests::element_pointer - std::int8_t]==]  )
set_tests_properties( [==[core::tests::element_pointer - std::int8_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::element_pointer - std::int32_t]==] /app/build-docker/core/tests/test_core [==[core::tests::element_pointer - std::int32_t]==]  )
set_tests_properties( [==[core::tests::element_pointer - std::int32_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::element_pointer - std::uint64_t]==] /app/build-docker/core/tests/test_core [==[core::tests::element_pointer - std::uint64_t]==]  )
set_tests_properties( [==[core::tests::element_pointer - std::uint64_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::element_pointer - float]==] /app/build-docker/core/tests/test_core [==[core::tests::element_pointer - float]==]  )
set_tests_properties( [==[core::tests::element_pointer - float]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::element_pointer - double]==] /app/build-docker/core/tests/test_core [==[core::tests::element_pointer - double]==]  )
set_tests_properties( [==[core::tests::element_pointer - double]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::get_set_element - std::int8_t]==] /app/build-docker/core/tests/test_core [==[core::tests::get_set_element - std::int8_t]==]  )
set_tests_properties( [==[core::tests::get_set_element - std::int8_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::get_set_element - std::int32_t]==] /app/build-docker/core/tests/test_core [==[core::tests::get_set_element - std::int32_t]==]  )
set_tests_properties( [==[core::tests::get_set_element - std::int32_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::get_set_element - std::uint64_t]==] /app/build-docker/core/tests/test_core [==[core::tests::get_set_element - std::uint64_t]==]  )
set_tests_properties( [==[core::tests::get_set_element - std::uint64_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::get_set_element - float]==] /app/build-docker/core/tests/test_core [==[core::tests::get_set_element - float]==]  )
set_tests_properties( [==[core::tests::get_set_element - float]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::get_set_element - double]==] /app/build-docker/core/tests/test_core [==[core::tests::get_set_element - double]==]  )
set_tests_properties( [==[core::tests::get_set_element - double]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::set_element_zero - std::int8_t]==] /app/build-docker/core/tests/test_core [==[core::tests::set_element_zero - std::int8_t]==]  )
set_tests_properties( [==[core::tests::set_element_zero - std::int8_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::set_element_zero - std::int32_t]==] /app/build-docker/core/tests/test_core [==[core::tests::set_element_zero - std::int32_t]==]  )
set_tests_properties( [==[core::tests::set_element_zero - std::int32_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::set_element_zero - std::uint64_t]==] /app/build-docker/core/tests/test_core [==[core::tests::set_element_zero - std::uint64_t]==]  )
set_tests_properties( [==[core::tests::set_element_zero - std::uint64_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::set_element_zero - float]==] /app/build-docker/core/tests/test_core [==[core::tests::set_element_zero - float]==]  )
set_tests_properties( [==[core::tests::set_element_zero - float]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::set_element_zero - double]==] /app/build-docker/core/tests/test_core [==[core::tests::set_element_zero - double]==]  )
set_tests_properties( [==[core::tests::set_element_zero - double]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::front_back_element - std::int8_t]==] /app/build-docker/core/tests/test_core [==[core::tests::front_back_element - std::int8_t]==]  )
set_tests_properties( [==[core::tests::front_back_element - std::int8_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::front_back_element - std::int32_t]==] /app/build-docker/core/tests/test_core [==[core::tests::front_back_element - std::int32_t]==]  )
set_tests_properties( [==[core::tests::front_back_element - std::int32_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::front_back_element - std::uint64_t]==] /app/build-docker/core/tests/test_core [==[core::tests::front_back_element - std::uint64_t]==]  )
set_tests_properties( [==[core::tests::front_back_element - std::uint64_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::front_back_element - float]==] /app/build-docker/core/tests/test_core [==[core::tests::front_back_element - float]==]  )
set_tests_properties( [==[core::tests::front_back_element - float]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::front_back_element - double]==] /app/build-docker/core/tests/test_core [==[core::tests::front_back_element - double]==]  )
set_tests_properties( [==[core::tests::front_back_element - double]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::iterators - std::int8_t]==] /app/build-docker/core/tests/test_core [==[core::tests::iterators - std::int8_t]==]  )
set_tests_properties( [==[core::tests::iterators - std::int8_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::iterators - std::int32_t]==] /app/build-docker/core/tests/test_core [==[core::tests::iterators - std::int32_t]==]  )
set_tests_properties( [==[core::tests::iterators - std::int32_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::iterators - std::uint64_t]==] /app/build-docker/core/tests/test_core [==[core::tests::iterators - std::uint64_t]==]  )
set_tests_properties( [==[core::tests::iterators - std::uint64_t]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::iterators - float]==] /app/build-docker/core/tests/test_core [==[core::tests::iterators - float]==]  )
set_tests_properties( [==[core::tests::iterators - float]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
add_test( [==[core::tests::iterators - double]==] /app/build-docker/core/tests/test_core [==[core::tests::iterators - double]==]  )
set_tests_properties( [==[core::tests::iterators - double]==] PROPERTIES WORKING_DIRECTORY /app/build-docker/core/tests)
set( test_core_TESTS core::tests::empty_buffer core::tests::memory_resource core::tests::copy_from_raw_pointer core::tests::copy_from_nullptr core::tests::copy_constructor core::tests::copy_capacity_larger_than_size core::tests::copy_constructor_explicit_memory_resource core::tests::copy_capacity_larger_than_size_explicit_memory_resource core::tests::move_constructor core::tests::move_assignment_to_default core::tests::move_assignment core::tests::self_move_assignment core::tests::resize_smaller [==[core::tests::resize bigger]==] [==[core::tests::reserve smaller]==] [==[core::tests::reserve bigger]==] [==[core::tests::unitialized - bool]==] [==[core::tests::unitialized - std::int8_t]==] [==[core::tests::unitialized - std::int16_t]==] [==[core::tests::unitialized - std::int32_t]==] [==[core::tests::unitialized - std::int64_t]==] [==[core::tests::unitialized - float]==] [==[core::tests::unitialized - double]==] [==[core::tests::initialValue - bool]==] [==[core::tests::initialValue - std::int8_t]==] [==[core::tests::initialValue - std::int16_t]==] [==[core::tests::initialValue - std::int32_t]==] [==[core::tests::initialValue - std::int64_t]==] [==[core::tests::initialValue - float]==] [==[core::tests::initialValue - double]==] [==[core::tests::const_ptr_data - bool]==] [==[core::tests::const_ptr_data - std::int8_t]==] [==[core::tests::const_ptr_data - std::int16_t]==] [==[core::tests::const_ptr_data - std::int32_t]==] [==[core::tests::const_ptr_data - std::int64_t]==] [==[core::tests::const_ptr_data - float]==] [==[core::tests::const_ptr_data - double]==] [==[core::tests::copy_ctor - bool]==] [==[core::tests::copy_ctor - std::int8_t]==] [==[core::tests::copy_ctor - std::int16_t]==] [==[core::tests::copy_ctor - std::int32_t]==] [==[core::tests::copy_ctor - std::int64_t]==] [==[core::tests::copy_ctor - float]==] [==[core::tests::copy_ctor - double]==] [==[core::tests::move_ctor - bool]==] [==[core::tests::move_ctor - std::int8_t]==] [==[core::tests::move_ctor - std::int16_t]==] [==[core::tests::move_ctor - std::int32_t]==] [==[core::tests::move_ctor - std::int64_t]==] [==[core::tests::move_ctor - float]==] [==[core::tests::move_ctor - double]==] [==[core::tests::set_value - bool]==] [==[core::tests::set_value - std::int8_t]==] [==[core::tests::set_value - std::int16_t]==] [==[core::tests::set_value - std::int32_t]==] [==[core::tests::set_value - std::int64_t]==] [==[core::tests::set_value - float]==] [==[core::tests::set_value - double]==] [==[core::tests::set_value_to_zero - bool]==] [==[core::tests::set_value_to_zero - std::int8_t]==] [==[core::tests::set_value_to_zero - std::int16_t]==] [==[core::tests::set_value_to_zero - std::int32_t]==] [==[core::tests::set_value_to_zero - std::int64_t]==] [==[core::tests::set_value_to_zero - float]==] [==[core::tests::set_value_to_zero - double]==] [==[core::tests::memory_resource - std::int8_t]==] [==[core::tests::memory_resource - std::int32_t]==] [==[core::tests::memory_resource - std::uint64_t]==] [==[core::tests::memory_resource - float]==] [==[core::tests::memory_resource - double]==] [==[core::tests::zero_size_constructor - std::int8_t]==] [==[core::tests::zero_size_constructor - std::int32_t]==] [==[core::tests::zero_size_constructor - std::uint64_t]==] [==[core::tests::zero_size_constructor - float]==] [==[core::tests::zero_size_constructor - double]==] [==[core::tests::non_zero_size_constructor - std::int8_t]==] [==[core::tests::non_zero_size_constructor - std::int32_t]==] [==[core::tests::non_zero_size_constructor - std::uint64_t]==] [==[core::tests::non_zero_size_constructor - float]==] [==[core::tests::non_zero_size_constructor - double]==] [==[core::tests::copy_constructor - std::int8_t]==] [==[core::tests::copy_constructor - std::int32_t]==] [==[core::tests::copy_constructor - std::uint64_t]==] [==[core::tests::copy_constructor - float]==] [==[core::tests::copy_constructor - double]==] [==[core::tests::resize_smaller - std::int8_t]==] [==[core::tests::resize_smaller - std::int32_t]==] [==[core::tests::resize_smaller - std::uint64_t]==] [==[core::tests::resize_smaller - float]==] [==[core::tests::resize_smaller - double]==] [==[core::tests::resize_larger - std::int8_t]==] [==[core::tests::resize_larger - std::int32_t]==] [==[core::tests::resize_larger - std::uint64_t]==] [==[core::tests::resize_larger - float]==] [==[core::tests::resize_larger - double]==] [==[core::tests::reserve_smaller - std::int8_t]==] [==[core::tests::reserve_smaller - std::int32_t]==] [==[core::tests::reserve_smaller - std::uint64_t]==] [==[core::tests::reserve_smaller - float]==] [==[core::tests::reserve_smaller - double]==] [==[core::tests::reserve_larger - std::int8_t]==] [==[core::tests::reserve_larger - std::int32_t]==] [==[core::tests::reserve_larger - std::uint64_t]==] [==[core::tests::reserve_larger - float]==] [==[core::tests::reserve_larger - double]==] [==[core::tests::resize_to_zero - std::int8_t]==] [==[core::tests::resize_to_zero - std::int32_t]==] [==[core::tests::resize_to_zero - std::uint64_t]==] [==[core::tests::resize_to_zero - float]==] [==[core::tests::resize_to_zero - double]==] [==[core::tests::release - std::int8_t]==] [==[core::tests::release - std::int32_t]==] [==[core::tests::release - std::uint64_t]==] [==[core::tests::release - float]==] [==[core::tests::release - double]==] [==[core::tests::element_pointer - std::int8_t]==] [==[core::tests::element_pointer - std::int32_t]==] [==[core::tests::element_pointer - std::uint64_t]==] [==[core::tests::element_pointer - float]==] [==[core::tests::element_pointer - double]==] [==[core::tests::get_set_element - std::int8_t]==] [==[core::tests::get_set_element - std::int32_t]==] [==[core::tests::get_set_element - std::uint64_t]==] [==[core::tests::get_set_element - float]==] [==[core::tests::get_set_element - double]==] [==[core::tests::set_element_zero - std::int8_t]==] [==[core::tests::set_element_zero - std::int32_t]==] [==[core::tests::set_element_zero - std::uint64_t]==] [==[core::tests::set_element_zero - float]==] [==[core::tests::set_element_zero - double]==] [==[core::tests::front_back_element - std::int8_t]==] [==[core::tests::front_back_element - std::int32_t]==] [==[core::tests::front_back_element - std::uint64_t]==] [==[core::tests::front_back_element - float]==] [==[core::tests::front_back_element - double]==] [==[core::tests::iterators - std::int8_t]==] [==[core::tests::iterators - std::int32_t]==] [==[core::tests::iterators - std::uint64_t]==] [==[core::tests::iterators - float]==] [==[core::tests::iterators - double]==])
