if(EXISTS "/app/build-docker/core/tests/test_core_tests-b12d07c.cmake")
  include("/app/build-docker/core/tests/test_core_tests-b12d07c.cmake")
else()
  add_test(test_core_NOT_BUILT-b12d07c test_core_NOT_BUILT-b12d07c)
endif()
