if(EXISTS "/app/build-docker/components/physical_plan_generator/tests/test_physical_plan_generator_tests-b12d07c.cmake")
  include("/app/build-docker/components/physical_plan_generator/tests/test_physical_plan_generator_tests-b12d07c.cmake")
else()
  add_test(test_physical_plan_generator_NOT_BUILT-b12d07c test_physical_plan_generator_NOT_BUILT-b12d07c)
endif()
