if(EXISTS "/app/build-docker/components/table/test/test_table_tests-b12d07c.cmake")
  include("/app/build-docker/components/table/test/test_table_tests-b12d07c.cmake")
else()
  add_test(test_table_NOT_BUILT-b12d07c test_table_NOT_BUILT-b12d07c)
endif()
